# Generated by Django 6.0.5 on 2026-05-29 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AL_DIA', 'Al día'), ('VENCIDO', 'Vencido'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_cobrar', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Depósito'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20)),
                ('numero_referencia', models.CharField(blank=True, max_length=100, verbose_name='# Boleta/Cheque')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='cuentas_cobrar.cuentacobrar')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha'],
            },
        ),
    ]
