# Generated by Django 6.0.5 on 2026-05-29 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=200)),
                ('telefono_destinatario', models.CharField(blank=True, max_length=50)),
                ('direccion_entrega', models.TextField()),
                ('transportista', models.CharField(blank=True, help_text='Nombre del transportista o empresa', max_length=100)),
                ('fecha_envio', models.DateField()),
                ('firma_recibido', models.TextField(blank=True, help_text='Nombre de quien recibe')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ItemEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('descripcion', models.CharField(max_length=300)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='envios.envio')),
            ],
            options={
                'verbose_name': 'Ítem de Envío',
                'verbose_name_plural': 'Ítems de Envío',
            },
        ),
    ]
