# Generated by Django 6.0.5 on 2026-05-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='costo_total',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='costo_total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ganancia_pp',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ganancia_total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='venta_total',
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
