# Generated by Django 6.0.5 on 2026-06-16 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_remove_cotizacion_venta'),
        ('ventas', '0002_remove_detalleventa_costo_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cotizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_generada', to='cotizaciones.cotizacion'),
        ),
    ]
