# Generated by Django 6.0.5 on 2026-06-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio venta 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio venta 3'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultima_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Última compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio venta 1'),
        ),
    ]
