# Generated by Django 6.0.5 on 2026-05-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.TextField(blank=True)),
                ('ruta', models.CharField(blank=True, choices=[('HUE_7', 'Huehuetenango 7'), ('HUE_17', 'Huehuetenango 17'), ('XELA_2', 'Quetzaltenango 2'), ('TOTO', 'Totonicapán'), ('SM', 'San Marcos'), ('OTRA', 'Otra')], max_length=20)),
                ('contacto', models.CharField(blank=True, help_text='Nombre de contacto', max_length=200)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
