# Generated by Django 6.0.5 on 2026-06-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
