# Generated by Django 6.0.5 on 2026-06-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_alter_detallecotizacion_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='venta',
        ),
    ]
